# Generated by Django 4.0.6 on 2022-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_n_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='n_predict',
            field=models.IntegerField(),
        ),
    ]
