# Generated by Django 4.0.6 on 2022-07-21 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_resultfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
