# Generated by Django 4.0.6 on 2022-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_resultfiles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
